version: '3'
services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      POSTGRES_URI: postgresql://postgres:postgres@localhost:5432/postgres
    restart: always
    volumes:
      - ./.docker/data/postgres:/var/lib/postgresql
    networks:
      - default
      